set -g default-terminal "tmux-256color"
set -sg terminal-overrides ",*:RGB"
set -g mouse on
set -g mode-keys vi
set -g status-style "bg=default fg=white"
set-option -g status-right ""
set -g pane-border-style "fg=default bg=default"
set -g pane-active-border-style "fg=default bg=default"
set -g set-clipboard on
set -g history-limit 50000
set -g display-time 4000
set -g focus-events on
set -s escape-time 0

set -g status on
set -g status-interval 5
set -g status-position top
set -g window-status-current-format " #[fg=#ffffff,bold,underscore]#I:#W"
set -g window-status-format " #I:#W"
set -g status-style "bg=default,fg=#dddddd"

set -g status-left "❯ #[fg=green,bold]#S #[fg=#dddddd,nobold]|"
set -g status-left-length 30

set -g status-right-length 80
set -g status-right "TEMP #(vcgencmd measure_temp | sed 's/.*=//') | \
CPU #(ps -A -o %cpu | awk '{s+=$1} END {printf \"%d%%\", s}')% | \
RAM #(free -h | awk '/Mem/ {print \$3\"/\"\$2}')"

